//
// AvailableFunction.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AvailableFunction: Codable {

    public var dataLog: Bool?
    public var debug: Bool?

    public init(dataLog: Bool?, debug: Bool?) {
        self.dataLog = dataLog
        self.debug = debug
    }


}

