//
// AvailablePowerSource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum AvailablePowerSource: String, Codable {
    case dcPower = "DC_POWER"
    case s3P = "S3P"
    case acExternalPower = "AC_EXTERNAL_POWER"

}
