//
// CloudConnectionMode.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum CloudConnectionMode: String, Codable {
    case generic = "GENERIC"
    case ibmBluemix = "IBM_BLUEMIX"
    case microsoftAzure = "MICROSOFT_AZURE"
    case amazonAws = "AMAZON_AWS"

}
