//
// InterfaceLock.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InterfaceLock: Codable {

    public var resourceFactory: Bool?
    public var resourceLogUid: Bool?
    public var factoryReset: Bool?
    public var hashPassword: Bool?
    public var scramActivated: Bool?

    public init(resourceFactory: Bool?, resourceLogUid: Bool?, factoryReset: Bool?, hashPassword: Bool?, scramActivated: Bool?) {
        self.resourceFactory = resourceFactory
        self.resourceLogUid = resourceLogUid
        self.factoryReset = factoryReset
        self.hashPassword = hashPassword
        self.scramActivated = scramActivated
    }


}

