//
// NfcPairingMode.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** NFC pairing obligatoire. Can be No: .... mandatory : must com on NFC before switching to other protocol. NFC Login mandatory : must use NFC for Login commands. (not relogging) */
public enum NfcPairingMode: String, Codable {
    case no = "NO"
    case mandatory = "MANDATORY"
    case mandatoryForLogin = "MANDATORY_FOR_LOGIN"

}
