//
// TargetCoreType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum TargetCoreType: String, Codable {
    case m0Cortex = "M0_CORTEX"
    case m1Cortex = "M1_CORTEX"
    case m3Cortex = "M3_CORTEX"
    case m2Cortex = "M2_CORTEX"

}
