//
// TargetProtocol.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum TargetProtocol: String, Codable {
    case swd = "SWD"
    case s3P = "S3P"
    case jtag = "JTAG"
    case modbus = "MODBUS"
    case gpio = "GPIO"
    case serialStandard = "SERIAL_STANDARD"
    case serialStandardSwd = "SERIAL_STANDARD_SWD"
    case serialStandardS3p = "SERIAL_STANDARD_S3P"

}
