//
// AclEntry.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AclEntry: Codable {

    public var read: Bool
    public var write: Bool
    public var execute: Bool
    public var delete: Bool
    public var create: Bool

    public init(read: Bool, write: Bool, execute: Bool, delete: Bool, create: Bool) {
        self.read = read
        self.write = write
        self.execute = execute
        self.delete = delete
        self.create = create
    }


}

