//
// CoreType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum CoreType: String, Codable {
    case m0Cortex = "M0_CORTEX"
    case m3Cortex = "M3_CORTEX"

}
