//
// FirmwareState.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum FirmwareState: String, Codable {
    case normal = "NORMAL"
    case updating = "UPDATING"
    case updated = "UPDATED"

}
