//
// LowPowerOptimisationLevel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum LowPowerOptimisationLevel: String, Codable {
    case no = "NO"
    case standby = "STANDBY"
    case shutdown = "SHUTDOWN"

}
