//
// NetworkMode.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum NetworkMode: String, Codable {
    case peerToPeer = "PEER_TO_PEER"
    case infrastructureOnly = "INFRASTRUCTURE_ONLY"
    case infrastructureCloud = "INFRASTRUCTURE_CLOUD"

}
