//
// ReadWriteRights.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ReadWriteRights: Codable {

    public var read: Bool
    public var write: Bool

    public init(read: Bool, write: Bool) {
        self.read = read
        self.write = write
    }


}

