//
// TargetComStats.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TargetComStats: Codable {

    public var nbFailCom: Int?
    public var nbSuccessfulCom: Int?

    public init(nbFailCom: Int?, nbSuccessfulCom: Int?) {
        self.nbFailCom = nbFailCom
        self.nbSuccessfulCom = nbSuccessfulCom
    }


}

