// APIs.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

open class API {
    open static var basePath = "https://localhost"
    //open static var credential: URLCredential?
    open static var customHeaders: [String:String] = [:]
    // open static var requestBuilderFactory: RequestBuilderFactory = AlamofireRequestBuilderFactory()
}


//public protocol RequestBuilderFactory {
//    func getNonDecodableBuilder<T>() -> RequestBuilder<T>.Type
//    func getBuilder<T:Decodable>() -> RequestBuilder<T>.Type
//}
