//
// AdpAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class AdpAPI {
    /**
     Read target status
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getAdpStatus(completion: @escaping ((_ data: Bytes?,_ error: Error?) -> Void)) {
        getAdpStatusWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Read target status
     - GET /target/adp/status
     - examples: [{contentType=application/json, example=""}]

     - returns: RequestBuilder<Bytes> 
     */
    open class func getAdpStatusWithRequestBuilder() -> RequestBuilder<Bytes> {
        let path = "/target/adp/status"
        let URLString = ClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Bytes>.Type = ClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
