//
// BundleAPI.swift
//
// Generated by iotize device api codegen
//

import Foundation
// 



open class BundleAPI {


    /**
    * Get acls
    * 
    * LWM2M path: /1028/{tupId}

    * @param bundleId input

    * @param groupId input
    * @return  api call
    */
    public func getAclgroupId(
        bundleId: Int, groupId: Int
    ) -> ApiRequest<Void>{
        
        // TODO replace path parameter
        //"bundleId": bundleId
        
        // TODO replace path parameter
        //"groupId": groupId
        

        return ApiRequest(
            method: TapRequestHeader.MethodType.GET
            , path: "/bundle/{bundleId}/acl/{groupId}"
            
            
        )
    }
    /**
    * Get datalog period
    * 
    * LWM2M path: /1028/{bundleId}/2

    * @param bundleId input
    * @return Int api call
    */
    public func getDatalogPeriod(
        bundleId: Int
    ) -> ApiRequest<Int>{
        
        // TODO replace path parameter
        //"bundleId": bundleId
        

        return ApiRequest(
            method: TapRequestHeader.MethodType.GET
            , path: "/bundle/{bundleId}/datalog-period"
            
        )
    }
    /**
    * Get bundle values
    * 
    * LWM2M path: /1028/{bundleId}/1

    * @param bundleId input
    * @return Bytes api call
    */
    public func getValues(
        bundleId: Int
    ) -> ApiRequest<Bytes>{
        
        // TODO replace path parameter
        //"bundleId": bundleId
        

        return ApiRequest(
            method: TapRequestHeader.MethodType.GET
            , path: "/bundle/{bundleId}/values"
            
        )
    }
    /**
    * Write acls
    * 
    * LWM2M path: /1028/{bundleId}/0/{groupId}
    * Body converter id: "ReadWriteRights"

    * @param bundleId input

    * @param groupId input

    * @param rights input
    * @return  api call
    */
    public func putAclgroupId(
        bundleId: Int, groupId: Int, rights: ReadWriteRights
    ) -> ApiRequest<Void>{
        
        // TODO replace path parameter
        //"bundleId": bundleId
        
        // TODO replace path parameter
        //"groupId": groupId
        

        return ApiRequest(
            method: TapRequestHeader.MethodType.PUT
            , path: "/bundle/{bundleId}/acl/{groupId}"
            
            
            , body: rights
        )
    }
    /**
    * Write datalog period
    * 
    * LWM2M path: /1028/{bundleId}/2
    * Body converter id: "integer_uint32"

    * @param bundleId input

    * @param value input
    * @return  api call
    */
    public func putDatalogPeriod(
        bundleId: Int, value: Int
    ) -> ApiRequest<Void>{
        
        // TODO replace path parameter
        //"bundleId": bundleId
        

        return ApiRequest(
            method: TapRequestHeader.MethodType.PUT
            , path: "/bundle/{bundleId}/datalog-period"
            
            , body: value
        )
    }

}
