//
// FirmwareAPI.swift
//
// Generated by iotize device api codegen
//

import Foundation
// 



open class FirmwareAPI {


    /**
    * Get state
    * 
    * LWM2M path: /5//3
    * @deprecated
    * @return FirmwareState api call
    */
    public func getState()
         -> ApiRequest<FirmwareState>{
        

        return ApiRequest(
            method: TapRequestHeader.MethodType.GET
            , path: "/firmware/state"
        )
    }
    /**
    * Get firmware update result
    * 
    * LWM2M path: /5//5
    * @deprecated
    * @return FirmwareUpdateResult api call
    */
    public func getUpdateResult()
         -> ApiRequest<FirmwareUpdateResult>{
        

        return ApiRequest(
            method: TapRequestHeader.MethodType.GET
            , path: "/firmware/update-result"
        )
    }
    /**
    * Check CRC
    * Compare le CRC attendu au CRC de la zone référencée. Modifie le Update Result (resource /5//5) à 1 si OK ou 5 si NG.
    * LWM2M path: /5//6
    * Body converter id: "CrcCheckBody"
    * @deprecated

    * @param data input
    * @return Bytes api call
    */
    public func postCrcCheck(
        data: CrcCheckBody
    ) -> ApiRequest<Bytes>{
        

        return ApiRequest(
            method: TapRequestHeader.MethodType.POST
            , path: "/firmware/crc-check"
            , body: data
        )
    }
    /**
    * Firmware package 
    * Firmware package : actif uniquement en mode update. Permet de transférer les données à programmer en flash pour l&#39;update firmware.
    * LWM2M path: /5//0
    * @deprecated
    * @return  api call
    */
    public func postPackage()
         -> ApiRequest<Void>{
        

        return ApiRequest(
            method: TapRequestHeader.MethodType.POST
            , path: "/firmware/package"
        )
    }
    /**
    * Update
    * Contrôle de l&#39;update: passage en mode update/updater/normal. Param: état futur souhaité. Actif uniquement si loggé en admin. (plus autres contraintes à définir: CRC check fait, etc.) Peut nécessiter un Reset du module
    * LWM2M path: /5//2
    * @deprecated
    * @return  api call
    */
    public func postUpdate()
         -> ApiRequest<Void>{
        

        return ApiRequest(
            method: TapRequestHeader.MethodType.POST
            , path: "/firmware/update"
        )
    }

}
