//
// VariableAPI.swift
//
// Generated by iotize device api codegen
//

import Foundation
// 



open class VariableAPI {


    /**
    * Get variable address
    * 
    * LWM2M path: /1029/{variableId}/0

    * @param variableId input
    * @return Int api call
    */
    public func getAddress(
        variableId: Int
    ) -> ApiRequest<Int>{
        
        // TODO replace path parameter
        //"variableId": variableId
        

        return ApiRequest(
            method: TapRequestHeader.MethodType.GET
            , path: "/variable/{variableId}/address"
            
        )
    }
    /**
    * Get variable bundle id
    * ID du bundle qui contient la variable
    * LWM2M path: /1029/{variableId}/6

    * @param variableId input
    * @return Int api call
    */
    public func getBundleId(
        variableId: Int
    ) -> ApiRequest<Int>{
        
        // TODO replace path parameter
        //"variableId": variableId
        

        return ApiRequest(
            method: TapRequestHeader.MethodType.GET
            , path: "/variable/{variableId}/bundle/id"
            
        )
    }
    /**
    * Get variable bundle values
    * 
    * LWM2M path: /1029/{variableId}/7

    * @param variableId input
    * @return Int api call
    */
    public func getBundleValues(
        variableId: Int
    ) -> ApiRequest<Int>{
        
        // TODO replace path parameter
        //"variableId": variableId
        

        return ApiRequest(
            method: TapRequestHeader.MethodType.GET
            , path: "/variable/{variableId}/bundle/values"
            
        )
    }
    /**
    * Get access rights for the variable
    * Get access rights for the variable (read and write)
    * LWM2M path: /1029/{variableId}/3

    * @param variableId input
    * @return ReadWriteRights api call
    */
    public func getCurrentAccess(
        variableId: Int
    ) -> ApiRequest<ReadWriteRights>{
        
        // TODO replace path parameter
        //"variableId": variableId
        

        return ApiRequest(
            method: TapRequestHeader.MethodType.GET
            , path: "/variable/{variableId}/current-access"
            
        )
    }
    /**
    * Get data format for variable
    * 
    * LWM2M path: /1029/{variableId}/1

    * @param variableId input
    * @return Int api call
    */
    public func getFormat(
        variableId: Int
    ) -> ApiRequest<Int>{
        
        // TODO replace path parameter
        //"variableId": variableId
        

        return ApiRequest(
            method: TapRequestHeader.MethodType.GET
            , path: "/variable/{variableId}/format"
            
        )
    }
    /**
    * Get variable array size
    * Get the number of element of the variable
    * LWM2M path: /1029/{variableId}/2

    * @param variableId input
    * @return Int api call
    */
    public func getNumberOfElements(
        variableId: Int
    ) -> ApiRequest<Int>{
        
        // TODO replace path parameter
        //"variableId": variableId
        

        return ApiRequest(
            method: TapRequestHeader.MethodType.GET
            , path: "/variable/{variableId}/number-of-elements"
            
        )
    }
    /**
    * Get variable value
    * Value of array of values. The size depends of variable format
    * LWM2M path: /1029/{variableId}/4

    * @param variableId input
    * @return Bytes api call
    */
    public func getValue(
        variableId: Int
    ) -> ApiRequest<Bytes>{
        
        // TODO replace path parameter
        //"variableId": variableId
        

        return ApiRequest(
            method: TapRequestHeader.MethodType.GET
            , path: "/variable/{variableId}/value"
            
        )
    }
    /**
    * Write variable address
    * 
    * LWM2M path: /1029/{variableId}/0
    * Body converter id: "integer_uint32"

    * @param variableId input

    * @param address input
    * @return  api call
    */
    public func putAddress(
        variableId: Int, address: Int
    ) -> ApiRequest<Void>{
        
        // TODO replace path parameter
        //"variableId": variableId
        

        return ApiRequest(
            method: TapRequestHeader.MethodType.PUT
            , path: "/variable/{variableId}/address"
            
            , body: address
        )
    }
    /**
    * Write variable bundle id
    * 
    * LWM2M path: /1029/{variableId}/6
    * Body converter id: "integer_uint32"

    * @param variableId input

    * @param value input
    * @return  api call
    */
    public func putBundleId(
        variableId: Int, value: Int
    ) -> ApiRequest<Void>{
        
        // TODO replace path parameter
        //"variableId": variableId
        

        return ApiRequest(
            method: TapRequestHeader.MethodType.PUT
            , path: "/variable/{variableId}/bundle/id"
            
            , body: value
        )
    }
    /**
    * Set data format of the variable
    * 
    * LWM2M path: /1029/{variableId}/1
    * Body converter id: "integer_uint8"

    * @param variableId input

    * @param value input
    * @return  api call
    */
    public func putFormat(
        variableId: Int, value: Int
    ) -> ApiRequest<Void>{
        
        // TODO replace path parameter
        //"variableId": variableId
        

        return ApiRequest(
            method: TapRequestHeader.MethodType.PUT
            , path: "/variable/{variableId}/format"
            
            , body: value
        )
    }
    /**
    * Write variable array size
    * Set the number of element of the variable
    * LWM2M path: /1029/{variableId}/2
    * Body converter id: "integer_uint8"

    * @param variableId input

    * @param value input
    * @return  api call
    */
    public func putNumberOfElements(
        variableId: Int, value: Int
    ) -> ApiRequest<Void>{
        
        // TODO replace path parameter
        //"variableId": variableId
        

        return ApiRequest(
            method: TapRequestHeader.MethodType.PUT
            , path: "/variable/{variableId}/number-of-elements"
            
            , body: value
        )
    }
    /**
    * Set variable value
    * 
    * LWM2M path: /1029/{variableId}/4
    * Body converter id: "Bytes"

    * @param variableId input

    * @param value input
    * @return  api call
    */
    public func putValue(
        variableId: Int, value: Bytes
    ) -> ApiRequest<Void>{
        
        // TODO replace path parameter
        //"variableId": variableId
        

        return ApiRequest(
            method: TapRequestHeader.MethodType.PUT
            , path: "/variable/{variableId}/value"
            
            , body: value
        )
    }
    /**
    * Set variable value
    * Difference with put ? 
    * LWM2M path: /1029/{variableId}/5
    * Body converter id: "Bytes"

    * @param variableId input

    * @param value input
    * @return  api call
    */
    public func setValue(
        variableId: Int, value: Bytes
    ) -> ApiRequest<Void>{
        
        // TODO replace path parameter
        //"variableId": variableId
        

        return ApiRequest(
            method: TapRequestHeader.MethodType.POST
            , path: "/variable/{variableId}/set-value"
            
            , body: value
        )
    }

}
